export const LEPTOS_DEVTOOLS_MESSAGE = "LEPTOS_DEVTOOLS_MESSAGE"
export const LEPTOS_DEVTOOLS_ON_MESSAGE = "LEPTOS_DEVTOOLS_ON_MESSAGE"

export const enum ConnectionName {
    Content = "LEPTOS_DEVTOOLS_CONTENT",
    Devtools = "LEPTOS_DEVTOOLS_DEVTOOLS",
    Developer = "LEPTOS_DEVTOOLS_DEVELOPER",
}
