export const LEPTOS_DEVTOOLS_MESSAGE = "LEPTOS_DEVTOOLS_MESSAGE"
export const LEPTOS_DEVTOOLS_ON_MESSAGE = "LEPTOS_DEVTOOLS_ON_MESSAGE"
export const LEPTOS_DEVTOOLS_DEVTOOLS = "LEPTOS_DEVTOOLS_DEVTOOLS"
export const LEPTOS_DEVTOOLS_DEVELOPER_TOOLS = "LEPTOS_DEVTOOLS_DEVELOPER_TOOLS"

export const enum ConnectionName {
    Content = "LEPTOS_DEVTOOLS_CONTENT",
    Popup = "LEPTOS_DEVTOOLS_POPUP",
}
